version: '3.8'
services: #サービスの設定
  web:
    depends_on: 
      - app
    image: nginx:1.15.6
    ports:
      - "8000:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html

  app:
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./laravel:/var/www/html

  mysql:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  mysql-data:
